[package]
name = "cl"
version = "0.1.0"
authors = ["Sean Kaufman <sean.kaufman92@gmail.com>"]
edition = "2018"

[dependencies]
ws="0.9"
ron = "0.5"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
paste = "0.1"